### ISSUE TITLE
updating to use the new API

### ISSUE THREAD

**Issue by ekg** [hhamud/ChatGPT-mode#1]
If you plan on updating this, you'll save others some coding effort to match the new chatgpt API endpoint.

**Comment by hhamud** [comment]
> If you plan on updating this, you'll save others some coding effort to match the new chatgpt API endpoint.

Initially, I was not going to update this to match the API as it was too cost prohibitive for me to use personally but with the new update and pricing, I may do so in the future. 

Though PRs are accepted here if you have plans on implementing this yourself.
